BACKEND-14: Чистая архитектура
go-park-mail-ru/2024_2_42 pull request #12
Opened 2024-10-16 14:42 UTC by wiseStann

Переписал приложение на чистую архитектуру

2024-10-17 16:47 UTC, TheVovchenskiy requested changes

2024-10-17 16:47 UTC, TheVovchenskiy commented on README.md
> +### [Деплой](http://localhost:8079/)
🤔 Точно localhost?

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/app/delivery/http/delivery.go
> +)
Если мы делаем интерфейсы, то их определение ложится на "заказчика", то есть они должны лежать там, где они должны использоваться.

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/app/usecase/usecase.go
> +)
То же самое и здесь, надо вынести эти интерфейсы в слой delivery, так как именно там определяется взаимодействие с юзкейсами

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/app/repository/repository.go
> +)
А эти интерфейсы надо определять на уровне юзкейсов

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/models/pin.go
По какой логике модели не помещаются в app директорию? Это не замечание, просто интересно)

2024-10-17 16:47 UTC, TheVovchenskiy commented on cmd/main.go
>  }
Какой-то жирненьки main получается. Вы тут прямо все делаете: инициализируете и деливери и юзкейсы и репозитории. Давайте стремиться к маленькому main) Вынеси все куда-то отдельно и разгреби логически инициализации, чтобы удобнее было во всем этом ориентироваться, а то потом у вас это дело распухнет и будет тяжкова-то)

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/app/delivery/http/user.go
> +	}
не очень мне нравится эта штука, в каждом хендлере такой копипаст, надо бы хотя бы в отдельную функцию вынести это везде. А потом это в мидлварены перенести

И вообще это дело лучше не хардкодить так, подобные штуки хотелось бы как-то гибко конфигурировать. Посмотрите какие-нибудь готовые библиотеки, как у них это реализовано и попробуйте что-то похожее сделать (например [вот](https://github.com/rs/cors), но можете еще что-то посмотреть)

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/app/delivery/http/user.go
> +		Name:     "session_token",
вот это как будто в константы можно положить

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/app/delivery/http/user.go
> +		Expires:  time.Now().Add(72 * time.Hour),
и это

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/app/repository/session.go
> +var SECRET = []byte(os.Getenv("JWT_SECRET"))
давай такие вещи определять на уровне конфига

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/app/repository/session.go
> +const SessionTokenExpirationTime = time.Hour * 72
и такие

Просто намного удобнее держать все такие значения в одном месте, даже если вы их хардкодите. Но вообще конечно лучше давать возможность их определять из вне, просто делать значения по-умолчанию

2024-10-17 16:47 UTC, TheVovchenskiy commented on internal/app/delivery/http/user.go
> +		Expires:  time.Now().Add(72 * time.Hour),
А такие значения тоже можно в конфиг класть по аналогичному принципу

2024-10-17 19:54 UTC, wiseStann commented on README.md
> +### [Деплой](http://localhost:8079/)
Ну я тестирую на локалке ведь) Из дева в мейн будем с айпишником переливать)

2024-10-17 21:40 UTC, wiseStann commented on internal/app/delivery/http/user.go
> +	}
Да, я это в миддлвары в следующей таске постараюсь перенести

2024-10-18 17:28 UTC, TheVovchenskiy approved these changes
норм, аппрув

2024-10-18 17:28 UTC, TheVovchenskiy commented on internal/app/tests/feed_test.go
>  	"testing"                // Импортируем пакет, где определена функция Feed
это уже прямо очень подробно коментируешь) ничего против не имею, но коменты на импортах как будто уже лишнее

2024-10-18 18:18 UTC, merged