BACKEND-13:Docker compose
go-park-mail-ru/2024_2_42 pull request #13
Opened 2024-10-16 18:03 UTC by ironyyyr

Создать Dockerfile и настроить запуск контейнера с бэкенд приложением через docker compose

2024-10-17 16:53 UTC, TheVovchenskiy requested changes

2024-10-17 16:53 UTC, TheVovchenskiy commented on build/DockerfileMain
а почему называется DockerfileMain, а не просто Dockerfile?

2024-10-17 16:53 UTC, TheVovchenskiy commented on build/DockerfileMain
> +FROM alpine AS runner
как ты указываешь версию здесь:

> `FROM golang:1.23-alpine AS builder`

давай тут также указывать конкрентую версию, это полезно для обратно совместимости, а то скачается новая версия, а там что-то разработчики поменяли и будет не очень хорошо.

2024-10-17 18:43 UTC, ironyyyr commented on build/DockerfileMain
потому что будут еще докерфайлы для бд и тд

2024-10-18 14:02 UTC, TheVovchenskiy approved these changes

2024-10-18 14:02 UTC, TheVovchenskiy commented on docker-compose.yml
> +      dockerfile: ./build/DockerfileMain
вот здесь тогда тоже поменяй название

2024-10-18 15:10 UTC, merged