BACKEND-25-Migration
go-park-mail-ru/2024_2_42 pull request #19
Opened 2024-10-28 19:47 UTC by ironyyyr

Настроить мигратор
Для удобной работы с миграциями бд надо настроить мигратор. На курсе СУБД предлагается два мигратора:

2024-10-28 23:06 UTC, TheVovchenskiy requested changes

2024-10-28 23:06 UTC, TheVovchenskiy commented on Makefile
> +	migrate -source file://db/migrations -database "postgres://postgres:12345@localhost:5432/2024_2_42?sslmode=disable" up 1
очень нехорошо, когда в октрытом виде есть урл подключения к постгре. Давайте будем собирать этот урл из переменнных окружения?)

Не помню, как у вас делано в самом приложении, надеюсь там тоже вы не хардкодите урл)

2024-10-29 09:57 UTC, ironyyyr commented on Makefile
> +	migrate -source file://db/migrations -database "postgres://postgres:12345@localhost:5432/2024_2_42?sslmode=disable" up 1
поправил, не хотело видеть переменные из .env ни на винде, ни на линуксе

2024-10-29 11:08 UTC, TheVovchenskiy approved these changes

2024-10-29 11:20 UTC, merged