BACKEND-4: Реализовал регистрацию
go-park-mail-ru/2024_2_42 pull request #5
Opened 2024-09-26 19:07 UTC by wiseStann

Добавлена функция SignUp, а так же введены ошибки в соответствующем пакете

2024-09-26 19:16 UTC, ironyyyr commented on internal/handlers/registration.go
> +	registeredUsers = append(registeredUsers, user)
Обернуть в мьютех, мб...

2024-09-26 23:43 UTC, TheVovchenskiy requested changes

2024-09-26 23:43 UTC, TheVovchenskiy commented on internal/handlers/registration.go
> +	password := r.FormValue("password")
в требованиях написано принимать и отправлять json, form data не пойдет

2024-09-26 23:43 UTC, TheVovchenskiy commented on internal/handlers/registration.go
> +	w.Write([]byte("Registration successfull"))
тут тоже нужен json, также возможно можно отправлять id пользователя

2024-09-26 23:43 UTC, TheVovchenskiy commented on internal/handlers/registration.go
> +		http.Error(w, err.Error(), errors.ErrorToHttpStatusCode[err])
вот тут при отправке ошибок пользователю осторожнее, далее у вас логика будет сложнее с бд и прочими компонентами. Мы не всегда хотим отдавать пользователю подробные ошибки о нашей внутрянке. В таких случаях можно сделать какой-то более хитрый маппер внутренних ошибок к внешним. 

Также я оставлю вам вот такую [ссылку](https://boldlygo.tech/posts/2024-01-08-error-handling/) на статью, в которой показано интересное решение вопроса с ошибками. Тут не то что бы решается проблема со скрытием внутренних ошибок от пользователя, но зато описано интересное решение с оберткой вокруг хэндлеров. Не обязательно это реализовывать у себя, но может это вдохновит вас на что-то интересное)

2024-09-26 23:43 UTC, TheVovchenskiy commented on internal/router/router.go
>  	fmt.Println("starting server at :8080")
тут захардкодили порт

2024-09-26 23:43 UTC, TheVovchenskiy commented on internal/router/router.go
>  	router.HandleFunc("/logout/{id:[0-9]+}", handlers.LogOut)
я вот сейчас немного засомневался, а зачем вам у логаута id? Если пользователь авторизован, то он присылает куки/токен, и по нему определяется текущий пользователь

2024-09-28 09:28 UTC, TheVovchenskiy approved these changes
Поправьте там в одном месте, а так аппрув

2024-09-28 09:28 UTC, TheVovchenskiy commented on internal/handlers/registration.go
> +	w.Write(respJSON)
давайте вынесем отправку json как-нибудь, чтобы можно было удобно переиспользовать это в других хендлерах

2024-09-28 12:27 UTC, merged