BACKEND-5: Реализовал авторизацию, рабочие сессии
go-park-mail-ru/2024_2_42 pull request #6
Opened 2024-09-26 21:41 UTC by ironyyyr

Добавить бизнес логику на авторизацию. Сессии так же хранятся в памяти.

2024-09-26 23:59 UTC, TheVovchenskiy requested changes

2024-09-26 23:59 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
> +		Expires:  time.Now().Add(72 * time.Hour),
давай длительность жизни уберем в константы

2024-09-26 23:59 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
> +	}
чтобы такое каждый раз не прописывать у гориллы мукс есть возможно сть https://pkg.go.dev/github.com/gorilla/mux#Route.Methods

2024-09-26 23:59 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
> +	cryptedToken, err := token.SignedString(SECRET)
не crypted, а signed

2024-09-26 23:59 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
> +		"exp":      time.Now().Add(time.Hour * 72).Unix(), // токен действителен 72 часа
сейчас это делать не надо, но подумайте над тем, чтобы в будущем добавить access tokens и refresh tokens

2024-09-26 23:59 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
> +		"username": user.UserName,
может здесь еще id пользователя делать?

2024-09-26 23:59 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
> +	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
а вообще я бы вынес claims как отдельную структуру, в которой встроен jwt.Claims, чтобы это была переисользуемая модель токена

2024-09-26 23:59 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
> +	w.Write([]byte("Login successful"))
отдаем json

2024-09-26 23:59 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
>  func LogOut(w http.ResponseWriter, r *http.Request) {
а тут не надо проверку делать, что пользователь авторизован?

2024-09-26 23:59 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
> +		w.Write([]byte("Successfully authorized as " + username))
json + id отдаем

2024-09-28 16:40 UTC, TheVovchenskiy approved these changes
Все хорошо, аппрув

2024-09-28 16:40 UTC, TheVovchenskiy commented on internal/handlers/authentication.go
> +		if user.UserName == req.Email && user.Password == req.Password {
не понял, почему `user.UserName == req.Email`? Если это так и задумано, то может стоит подумать, чтобы переименовать переменные, а то прямо непонятно, почему username c email сравнивается

2024-09-28 16:54 UTC, wiseStann commented on internal/handlers/authentication.go
> +		if user.UserName == req.Email && user.Password == req.Password {
Это невнимательность...

2024-09-28 17:04 UTC, merged